import type {Metadata} from 'next';
import {LegalPage,LegalSection} from '@/components/legal-page';
import {business} from '@/lib/data';

export const metadata:Metadata={title:'Terms and Conditions',description:'Terms governing use of the Rugged American Exteriors website and online service information.'};

export default function Terms(){return <LegalPage title="Terms and Conditions" description="Clear terms for using this website and requesting home service information.">
  <LegalSection title="Agreement to these terms"><p>By using this website, you agree to these terms. If you do not agree, please do not use the website. These website terms are separate from any estimate, work authorization, contract, warranty, financing agreement, or other document signed for a project. A signed project document controls if it conflicts with general website content.</p></LegalSection>
  <LegalSection title="Website information"><p>We work to keep service descriptions, photos, pricing information, and other content accurate. Website content is general information and may not reflect the conditions at your property. Services, materials, colors, availability, and service areas may change without notice. Photos may show representative work and do not promise an identical result.</p></LegalSection>
  <LegalSection title="Estimate and inspection requests"><p>Submitting a form, scheduling an inspection, or discussing a project does not create a contract or require either party to proceed. Free inspections and estimates are subject to availability, safe access, property conditions, and the scope requested. A project begins only after the required written agreement is accepted.</p></LegalSection>
  <LegalSection title="Cash estimates, pricing, and payments"><p>A cash bid is based on the information and conditions known when it is prepared. Hidden damage, code requirements, customer changes, material changes, or conditions discovered during work may require a written change to scope and price. Deposit, progress payment, final payment, cancellation, and collection terms will be stated in the applicable project agreement. The website does not currently accept payments.</p></LegalSection>
  <LegalSection title="Insurance related roofing work"><p>We may inspect damage, document findings, prepare a construction estimate, communicate with an adjuster or carrier when authorized, and help you understand the roofing process. We are not your insurance carrier, public adjuster, lawyer, or coverage decision maker. We do not promise that a claim will be approved or guarantee a payment amount. Coverage, deductibles, depreciation, exclusions, and claim decisions are determined by your policy and insurance carrier.</p><p>You remain responsible for reviewing carrier communications, complying with policy duties, selecting a contractor, and paying amounts required by your project agreement.</p></LegalSection>
  <LegalSection title="Scheduling and property access"><p>Project dates may be affected by weather, material availability, permitting, inspections, safety conditions, or events outside reasonable control. Customers are responsible for providing authorized and reasonably safe access to the work area and identifying known hazards, concealed utilities, pets, or other conditions that could affect the work.</p></LegalSection>
  <LegalSection title="Warranties"><p>Any workmanship or manufacturer warranty applies only when provided in writing and is subject to its stated coverage, exclusions, maintenance requirements, transfer rules, and claim process. Website statements do not create an additional warranty. Manufacturer warranties are administered under the manufacturer’s terms.</p></LegalSection>
  <LegalSection title="Acceptable website use"><p>You may use this website for lawful personal or business purposes related to our services. Do not attempt to disrupt the website, bypass security, introduce harmful code, scrape content at unreasonable volume, impersonate another person, submit false requests, or use our content or branding without permission.</p></LegalSection>
  <LegalSection title="Third party links and services"><p>Links to social networks, review platforms, maps, payment services, or other third parties are provided for convenience. We do not control their content, security, availability, or policies and are not responsible for your use of those services.</p></LegalSection>
  <LegalSection title="Intellectual property"><p>The website design, written content, branding, graphics, and original project photography are owned by Rugged American Exteriors or used with permission. You may view the website and share links to its public pages, but you may not copy, republish, sell, or falsely present the content as your own without written permission.</p></LegalSection>
  <LegalSection title="Disclaimers and limitation of liability"><p>The website is provided on an as available basis. To the fullest extent allowed by law, we disclaim implied warranties relating to the website itself and do not guarantee uninterrupted or error free access. Rugged American Exteriors will not be liable for indirect, incidental, special, consequential, or punitive damages arising only from website use or inability to use the website.</p><p>Nothing in these terms excludes liability that cannot legally be limited. Project related responsibilities and remedies are governed by the signed project documents and applicable law.</p></LegalSection>
  <LegalSection title="Texas law and changes"><p>These website terms are governed by Texas law, without regard to conflict of law rules. We may update them as the website or our practices change. The date at the top shows the latest revision.</p></LegalSection>
  <LegalSection title="Contact us"><p>Questions may be sent to <a className="font-bold text-oxide underline" href={`mailto:${business.email}`}>{business.email}</a> or <a className="font-bold text-oxide underline" href={`tel:${business.phoneHref}`}>{business.phone}</a>.</p></LegalSection>
</LegalPage>}
