import type {Metadata} from 'next';
import {LegalPage,LegalSection} from '@/components/legal-page';
import {business} from '@/lib/data';

export const metadata:Metadata={title:'Privacy Policy',description:'How Rugged American Exteriors collects, uses, and protects website and customer information.'};

export default function PrivacyPolicy(){return <LegalPage title="Privacy Policy" description="A straightforward explanation of the information we collect and how we use it.">
  <LegalSection title="Who this policy covers"><p>This policy applies to information collected through the Rugged American Exteriors website and through communications that begin on this website. It does not replace any privacy terms contained in a signed project agreement or a third party service.</p></LegalSection>
  <LegalSection title="Information you choose to provide"><p>When you request an estimate or contact us, we may collect your name, phone number, email address, property address or ZIP code, requested service, project details, preferred contact method, and any photo you upload. We may also retain messages, inspection notes, estimates, contracts, invoices, warranty information, and records of our communications when you become a customer.</p><p>Please do not submit highly sensitive information such as Social Security numbers, bank passwords, or complete payment card numbers through a website form.</p></LegalSection>
  <LegalSection title="How we use information"><p>We use information to respond to requests, schedule inspections, prepare estimates, communicate about projects, provide services, process authorized payments, maintain business and warranty records, improve the website, prevent fraud or misuse, meet legal obligations, and protect our customers and business.</p><p>If you select text messaging as your preferred contact method, we may text you about your request or project. Message and data rates may apply. You may ask us to stop nonessential texts at any time.</p></LegalSection>
  <LegalSection title="Contact forms and uploaded photos"><p>Estimate form submissions are sent to us through an email delivery provider. Uploaded project photos may be included with that message. We use this information to evaluate and respond to your request. Internet and email delivery cannot be guaranteed to be completely secure, so please call us if you are uncomfortable sending information online.</p></LegalSection>
  <LegalSection title="Cookies, analytics, and advertising"><p>The current website does not use an advertising pixel or a customer facing analytics platform. Basic technical logs may still be created by the website host for security, reliability, and performance.</p><p>If we later enable analytics, advertising, call tracking, or similar tools, those providers may use cookies or comparable technologies to understand visits, measure campaigns, prevent fraud, or show relevant advertising. We will update this policy and provide any notice or choice required by applicable law. You can also use browser controls to limit or delete cookies.</p></LegalSection>
  <LegalSection title="Third party services"><p>We may use service providers for website hosting, email delivery, scheduling, customer management, payment processing, accounting, analytics, advertising, and other business operations. These providers may process information only as needed to perform their services or as allowed by their own terms and applicable law.</p><p>Links to Facebook, Instagram, Google Reviews, and other outside websites take you to services we do not control. Their privacy policies apply once you leave our website.</p></LegalSection>
  <LegalSection title="Payments and insurance information"><p>The website does not currently collect online payments. If electronic payment options are offered, payment information may be handled directly by a payment processor, and we may receive limited transaction details rather than a complete card number.</p><p>If you ask for assistance with a roofing insurance claim, we may receive or share inspection findings, claim documents, estimates, measurements, photos, and communications with you, your carrier, adjuster, or other authorized participants. We use that information to support the roofing process. Your carrier and policy determine coverage and claim decisions.</p></LegalSection>
  <LegalSection title="Sharing and selling information"><p>We may share information with employees, crews, subcontractors, material suppliers, professional advisers, insurers, service providers, government authorities when required, and parties involved in a business transfer. We do not sell personal information for money. We do not share sensitive personal information for targeted advertising without any consent required by law.</p></LegalSection>
  <LegalSection title="Retention and security"><p>We keep information only as long as reasonably needed for the purposes described here, including customer service, warranties, accounting, insurance, dispute resolution, and legal compliance. We use reasonable administrative and technical safeguards, but no storage or transmission method can promise absolute security.</p></LegalSection>
  <LegalSection title="Your choices and requests"><p>You may ask to review, correct, or delete personal information we hold about you, subject to identity verification and legal or business recordkeeping requirements. Depending on where you live and which laws apply, you may have additional privacy rights. We will not discriminate against you for making a valid request.</p></LegalSection>
  <LegalSection title="Children"><p>This website is intended for homeowners and adults seeking home services. We do not knowingly collect personal information from children under 13.</p></LegalSection>
  <LegalSection title="Contact us"><p>For privacy questions or requests, email <a className="font-bold text-oxide underline" href={`mailto:${business.email}`}>{business.email}</a> or call <a className="font-bold text-oxide underline" href={`tel:${business.phoneHref}`}>{business.phone}</a>.</p></LegalSection>
</LegalPage>}
