export const business={name:'Rugged American Exteriors',area:'Dallas Fort Worth and the Surrounding Metroplex',phone:'(817) 512-9879',phoneHref:'+18175129879',email:'ruggedamericanexteriors@gmail.com',reviewsUrl:'https://g.page/r/Cc7eLpt0on81EAE/review',instagramUrl:'https://www.instagram.com/ruggedamericanexteriors?igsh=cG92dDNzcHlpNWo3&utm_source=qr',facebookUrl:'https://www.facebook.com/people/Rugged-American-Exteriors/61588841853561/'};
export const reviews=[
 {name:'Christi Gilpin',quote:'Caleb is very professional and easy to work with. Scheduling was a breeze, and the garage door looks great!'},
 {name:'Joyce Merrill',quote:'Caleb, James, and the entire team treated me so well. They were professional, thorough, and cleaned up everything when they were finished. I couldn’t have asked for a better experience. I feel very blessed that Caleb was sent my way, and I’m so happy that I’ll be having him complete more work for me. I would recommend them to anybody!'},
 {name:'Teresa Boba',quote:'Caleb came to my rescue! I was trying to DIY the project, so I called on Friday, and Caleb and Carlos came out on Saturday. They were on time, professional, personable, and even honored the spring discount. Next time, I’ll call Caleb first, DIY is harder than it looks! Thank you so much. Now I get to decorate my beautifully painted bathroom!'}
];
export const gutters=[
 {slug:'gutter-installation',name:'Gutter Installation',eyebrow:'THE MAIN EVENT',title:'Seamless gutters built around your home.',desc:'We measure your home, roll form each seamless gutter run onsite, and hand fabricate custom corners for a cleaner system built around your actual roofline.',items:['Seamless 5 inch and 6 inch systems formed onsite','Hand fabricated custom corners without strip miters','Complete replacement and custom layouts','Downspout installation and replacement','Color options selected for your exterior']},
 {slug:'gutter-repair',name:'Gutter Repair',eyebrow:'FIX THE WEAK POINT',title:'Stop leaks, sagging, and poor drainage.',desc:'We inspect the whole run, explain what is repairable, and recommend replacement only when it makes better sense.',items:['Leaks, separated corners, and seams','Loose or pulling away sections','Pitch and drainage corrections','Storm and downspout damage']},
 {slug:'gutter-guards',name:'Gutter Guards',eyebrow:'KEEP WATER MOVING',title:'Less debris. Easier maintenance.',desc:'Gutter protection can reduce leaf buildup and overflow. We help determine whether guards fit your trees, roof, and existing system.',items:['New and existing gutter systems','Options for local leaf and debris loads','Professional fit and installation','Practical ongoing maintenance guidance']},
 {slug:'gutter-cleaning',name:'Gutter Cleaning',eyebrow:'ROUTINE PROTECTION',title:'Clear the path before the next storm.',desc:'We remove debris, clear downspouts, and flag visible issues before a small problem becomes a water management headache.',items:['Leaf and roof-debris removal','Downspout flow check','Visible damage inspection','Seasonal North Texas maintenance']}
];
export const painting=[
 {slug:'painting-services',name:'Painting Services',title:'A cleaner process from prep to final walkthrough.',desc:'Interior, exterior, and cabinet painting with detailed preparation, trusted Sherwin-Williams products, and clear communication.',items:['Interior, exterior, and cabinet painting','Detailed surface preparation and protection','Sherwin-Williams product and color guidance','Professional application and final walkthrough']},
 {slug:'exterior-painting',name:'Exterior Painting',title:'A durable finish for North Texas exteriors.',desc:'Detailed exterior preparation and trusted Sherwin-Williams products selected to deliver a professional finish in North Texas conditions.',items:['Siding, trim, fascia, soffit, doors, and shutters','Cleaning, scraping, sanding, caulking, and priming as needed','Protection for landscaping, roofing, windows, and hard surfaces','Product, sheen, and color guidance','Careful application, cleanup, and final walkthrough']},
 {slug:'interior-painting',name:'Interior Painting',title:'Fresh color, careful protection, clean work areas.',desc:'From one room to the whole home, we combine careful protection, thoughtful color guidance, and trusted Sherwin-Williams products.',items:['Walls, ceilings, trim, doors, and accent areas','Furniture, flooring, fixture, and adjacent surface protection','Minor patching, sanding, caulking, and priming as needed','Product, sheen, and color guidance for each room','Organized application, daily cleanup, and final walkthrough']},
 {slug:'cabinet-painting',name:'Cabinet Painting',title:'Transform cabinets without a full replacement.',desc:'A preparation focused cabinet refinishing process using trusted Sherwin-Williams products selected for a smooth, durable finish.',items:['Kitchen, bathroom, and built in cabinetry','Detailed cleaning, labeling, sanding, and priming','Protection for counters, floors, walls, and appliances','Cabinet appropriate product, sheen, and color guidance','Controlled application, careful reassembly, and final walkthrough']}
];
export const other=[
 {slug:'roofing',name:'Roofing',title:'Straight answers about your roof.',desc:'Start with a free roof inspection, then choose a competitive cash bid or get practical help navigating a potential insurance claim.',items:['Free inspections for storm, hail, wind, and other roof damage','Competitive cash roofing estimates','Roof repair and complete replacement options','Claim process support and adjuster coordination','Clear guidance from inspection through installation']},
 {slug:'fencing',name:'Fencing',title:'Privacy, curb appeal, and dependable boundaries.',desc:'Fence installation, replacement, and repair for homes across the Metroplex.',items:['Wood privacy fencing','Fence and gate repairs','Full replacement and new installation','Staining or painting where applicable']},
 {slug:'concrete',name:'Concrete',title:'Concrete built for the way you use your property.',desc:'Residential and commercial concrete, form setting, pouring, demolition, foundations, slabs, driveways, patios, and decorative finishes.',items:['Form setting, pouring, and demolition','Residential and commercial concrete','Driveways, walkways, sidewalks, and slabs','Foundations, patios, pool decks, and decorative concrete']}
];
export const cities=['fort-worth','burleson','crowley','mansfield','arlington','cleburne','joshua','aledo','weatherford','granbury','benbrook','kennedale','midlothian','alvarado','godley'];
export const cityName=(s:string)=>s.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
export const allServices=[...gutters,...painting,...other];
export const serviceImages:Record<string,{src:string;alt:string}>={'gutter-installation':{src:'/service-images/gutter-installation.webp',alt:'Professional installing seamless gutters on a North Texas home'},'gutter-repair':{src:'/service-images/gutter-repair.webp',alt:'Technician repairing a gutter and downspout connection'},'gutter-guards':{src:'/service-images/gutter-guards.webp',alt:'Micro-mesh gutter guards being installed on a residential gutter'},'gutter-cleaning':{src:'/service-images/gutter-cleaning.webp',alt:'Professional removing leaves and debris during gutter cleaning'},'painting-services':{src:'/service-images/interior-painting.webp',alt:'Professional painter working in a carefully protected living room'},'interior-painting':{src:'/service-images/interior-painting.webp',alt:'Professional interior painting with furniture and floors protected'},'exterior-painting':{src:'/service-images/exterior-painting.webp',alt:'Exterior siding and trim being professionally painted'},'cabinet-painting':{src:'/service-images/cabinet-painting.webp',alt:'Cabinet doors prepared for a professional painted finish'},roofing:{src:'/service-images/roofing.webp',alt:'Professional inspecting an architectural shingle roof'},fencing:{src:'/service-images/fencing.webp',alt:'Craftsman installing a cedar privacy fence and gate'},concrete:{src:'/service-images/concrete.png',alt:'Finished concrete patio and flatwork at a North Texas property'}};
